# Generated by Django 4.1.13 on 2024-10-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_testmodel_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
